### ISSUE TITLE
Joda addon does not support Instant

### ISSUE THREAD

**Issue by benstpierre** [tminglei/slick-pg#100]
The joda addon does not support instant which is a highly usefull Joda type.  Often you just want to record when something happened and not worry about timezone.

**Comment by deanchen** [comment]
@tminglei this would be useful for me, pg's datetime with tz would be the best candidate.

**Comment by tminglei** [comment]
Ok, I'll implement it.

_But you may wait some time, since I'm very busy on an important project of my employer these days._

**Comment by pettyjamesm** [comment]
This isn't exactly the same issue, but I've noticed that even the `java.time.Instant` implementation seems to be using jdbc `getString` and then parsing the result. This seems to work, but seems to be creating more overhead than necessary since java.sql.Timestamp can be sent over the wire in binary format and has a `.toInstant` method on it.

**Comment by tminglei** [comment]
Well, sorry! I forgotten to implement it for so long time.
I'll implement ASAP.

**Comment by tminglei** [comment]
Hi all, implemented. pls help check it. _Thanks!_

**Comment by pettyjamesm** [comment]
I'm curious why https://github.com/tminglei/slick-pg/commit/16ac99c3d13309069dab91c96b6c16bfdd08f9cd#diff-34d5aecdb56ee5cade161615301e8560R56 is implemented to using `LocalDateTime.parse` from `String` since the underlying JDBC driver supports [Java 8 time library natively](https://jdbc.postgresql.org/documentation/head/8-date-time.html).

I know things can get tricky with time zones, but I've seen the parsing / serializing string operations show up in profiling sessions. I would think that the driver's implementation would allow binary transfer of timestamp values and converting from those would be more efficient.

**Comment by tminglei** [comment]
@pettyjamesm yes, you're right. I almost forget this.
I'll refactor to enhance it.

**Comment by tminglei** [comment]
@pettyjamesm well, we're wrong. This is for `joda-time` support, pg jdbc didn't support `joda-time`.
So I needn't refactor for it.

**Comment by pettyjamesm** [comment]
Sorry, I should have been more clear. My comment was definitely in the wrong thread. I was talking about the native suport for `java.time.LocalDateTime`. See https://jdbc.postgresql.org/documentation/head/8-date-time.html for details.

I noticed that there was some discussion around their use of the java.util.Calendar instance internally not being threadsafe in an old PR. Is that still what is requiring slick-pg to parse from `String`?

**Comment by tminglei** [comment]
@pettyjamesm refactored to use built-in `LocalDate/LocalTime/LocalDateTime/OffsetDateTime` support ([08018b](https://github.com/tminglei/slick-pg/commit/08018b292115b66e57a9ddeddfc6ba95510383d7)).
