### ISSUE TITLE
Slick 3.0 tsql type mapping

### ISSUE THREAD

**Issue by saosebastiao** [tminglei/slick-pg#176]
I'm trying to use the new typed sql statements in Slick 3.0 and I'm discovering that the type mapping that I have found in slick-pg doesn't seem to be working. Is this something to do with how I extend the postgres driver? Or is this something that needs direct support in slick-pg?

**Comment by tminglei** [comment]
Hi @saosebastiao, do you mean those extension methods not working?

_Those extension methods are based on `JdbcType`, but slick plain sql isn't based on it. So the types supported by slick-pg plain sql hasn't those extension methods._

**Comment by saosebastiao** [comment]
I'm not sure I understand your response, so I'll give a little more information. 

In the normal slick methodology, I could map a case class to a table like this:
    
    import org.joda.time._
    case class Foo(name: String, date: DateTime)
    class Foos(tag: Tag) extends Table[Foo](tag, "foos") {
      def name = column[String]("name")
      def date = column[DateTime]("date")
      def * = (name, date) <> (Foo.tupled, Foo.unapply)
    }
    val foos = TableQuery[Foos]

With the new slick 3.0 `tsql` typed sql statements, I would like to be able to write the following:

    def selectAllFoos:  DBIO[Seq[(String,DateTime)]] = tsql"select * from foos"

but in this case the type mapping that I have come to expect from slick-pg for the joda DateTime class doesn't work. 

Are you saying that the underlying JDBC functions are different between Slick's normal usage and its `tsql` statements? The methods used for marshalling case classes [as explained here](http://slick.typesafe.com/doc/3.0.0/sql.html#result-sets) look like they are using normal JDBC column data types.

**Comment by tminglei** [comment]
Well, I got your means.
I just check the related codes of `slick`, and seems it requires some special customization on `slick-pg`.

I'll implement it ASAP when I have time.

_Thanks for pointing it out! :-)_

**Comment by tminglei** [comment]
Hi @saosebastiao, to some degree, this is a problem same as #171, which requires `slick-pg` to auto bind a pg type to a scala type.
This is not so easy, as you know, since a pg type can be bound to multiple scala types.

I need more time to construct a mechanism to help do it easily when your customized postgres driver mixing some pg type supports. So it won't be ready soon.

**Comment by tminglei** [comment]
Hi @saosebastiao, the implement is almost done, but we need some enhancement in `slick`, related pull request is slick/slick#1226

The working branch in `slick-pg` is tsql, you can check its codes [here](https://github.com/tminglei/slick-pg/tree/tsql).

_BTW, currently I can only support bind a pg type to a scala type without type parameter.
For scala types with type parameter, I can't implement it, since it's not supported by `slick` by now._

**Comment by tminglei** [comment]
Hi @saosebastiao, the changes already merged into master and released in slick-pg v0.10.0-RC1.
You can help check it. Thanks! ^^

**Comment by saosebastiao** [comment]
Thanks, I'll test it out tonight. I appreciate the fast turnaround on this request!
