### ISSUE TITLE
MyPostgresDriver can't instantiate in play-scala example

### ISSUE THREAD

**Issue by nelsonblaha** [tminglei/slick-pg#199]
Trying to run the play-scala example, get Configuration Error "Cannot connect to database [default]" with stacktrace ending in the following:

Caused by: java.lang.ClassNotFoundException: util.MyPostgresDriver$

I have postgres running with a "test" database created as configured in the example's application.conf. Did I miss some setup?

**Comment by motns** [comment]
There's a problem with Play's classloader not finding the custom Postgres driver class, but only when running Play in dev mode (it works fine in production). This has been recently fixed in Slick version `3.0.1`, which is pulled in by updating the `play-slick` dependency to `1.0.1`.

I've submitted a PR to fix the example, but you can just update the dependency version in your `build.sbt` in the meantime.
