### ISSUE TITLE
PgRange doesn't support tstzrange type

### ISSUE THREAD

**Issue by davidlong-porch** [tminglei/slick-pg#302]
In PgRangeSupport.scala, we need an additional support for tstzrange type, including reading, setting, and querying tstzrange in the where clauses.  Thank you!

**Comment by tminglei** [comment]
Well, supporting tstzrange will require java 8, since before java 8, there isn't a suitable built-in time-zoned datetime type. Currently, it's required only when you want to use date2 addon.

I'll think to add it in next major release. But now you'd better to do it yourself.

_For how to implement it you can refer to current implementation codes. Any problem you pls let me know._

**Comment by Trekoid** [comment]
@tminglei We tried to implement tstzrange, but seem to have missed something that triggers an implicit conversion. Could you point out what we are missing?
See my branch at https://github.com/trekoid/slick-pg/tree/tstzrange
The project compiles okay. We are getting the following errors during the tests. It seems it isn't able to implicitly convert OffsetDateTime to RangeColumnExtensionMethods.

`Error:(68, 41) value @>^ is not a member of slick.lifted.Rep[Option[com.github.tminglei.slickpg.Range[java.time.OffsetDateTime]]]
          RangeTests.filter(_.tstzRange @>^ tstz("2011-10-01 15:30:00-07")).sortBy(_.id).to[List].result.map(
Error:(78, 60) value bind is not a member of java.time.OffsetDateTime
          RangeTests.filter(tstz("2011-10-01 15:30:00-07").bind <@^: _.tstzRange).sortBy(_.id).to[List].result.map(
Error:(78, 65) value <@^: is not a member of slick.lifted.Rep[Option[com.github.tminglei.slickpg.Range[java.time.OffsetDateTime]]]
          RangeTests.filter(tstz("2011-10-01 15:30:00-07").bind <@^: _.tstzRange).sortBy(_.id).to[List].result.map(`

**Comment by tminglei** [comment]
@Trekoid here's the codes to associate the type mapper with the extension methods:
```scala
    implicit def simpleRangeColumnExtensionMethods[B0](c: Rep[Range[B0]])(
      implicit tm: JdbcType[B0], tm1: JdbcType[Range[B0]]) = {
        new RangeColumnExtensionMethods[Range[B0], B0, Range[B0]](c)
      }
    implicit def simpleRangeOptionColumnExtensionMethods[B0](c: Rep[Option[Range[B0]]])(
      implicit tm: JdbcType[B0], tm1: JdbcType[Range[B0]]) = {
        new RangeColumnExtensionMethods[Range[B0], B0, Option[Range[B0]]](c)
      }
```

For Range[OffsetDateTime], it still requires `JdbcType[OffsetDateTime]`.

**Comment by Trekoid** [comment]
@tminglei I was able to implement by adding `JdbcType[OffsetDateTime]` support in PgDateSupport.scala. My branch at https://github.com/trekoid/slick-pg/tree/tstzrange is updated if you want to look. It needs some cleanup, as I copied the DateFormatters of the date2 module over and I want to make sure they map properly. All but one tests pass, and that one is failing due to an implicit timezone conversion happening. I would like to provide something you can merge into the project. In that vein, was it your intent to remove support for the previous types, or should both type mappings remain to support backwards compatibility?

**Comment by tminglei** [comment]
@Trekoid both types will be supported. But `PgDate2Support` may be provided as a default module instead of as an addon module.
